best_bank_as/urls.py
from django.urls import path

from best_bank_as import views

app_name = "best_bank_as"


urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.profile, name="profile"),
    path("accounts/", views.account_list, name="account_list"),
    path("accounts/<int:pk>/", views.account_details, name="account_details"),
    path(
        "staff/accounts/<int:pk>",
        views.staff_account_list,
        name="staff_account_list",
    ),
    path("staff/", views.staff_page, name="staff_page"),
    path("staff/customers", views.staff_customer_list, name="staff_customer_list"),
    path(
        "staff/customers/approve",
        views.customers_approve_list,
        name="customers_approve_list",
    ),
    path(
        "staff/customers/approve/<int:pk>",
        views.customers_approve_details,
        name="customers_approve_details",
    ),
    # TODO: Figure if register, should just be customer path
    path("customers/register/", views.customer_list, name="customer_register"),
    path("customers/", views.customer_list, name="customer"),
    path("customers/<int:pk>/", views.customer_details, name="customer"),
    # Loan applications
    path(
        "loan-applications",
        views.loan_application_list,
        name="loan_application_list",
    ),
    path(
        "loan-applications/<int:pk>",
        views.loan_application_details,
        name="loan_application_details",
    ),
    path(
        "staff/loan-applications/<int:pk>",
        views.staff_loan_application_details,
        name="staff_loan_application_details",
    ),
    path(
        "staff/loan-applications/",
        views.staff_loan_applications_list,
        name="approve_loan_applications",
    ),
    # Transfers
    path("transfer/", views.transaction_list, name="transfer_money"),
    path("external-transfer/", views.external_transfer, name="external-transfer"),
    # Auth
    path("auth-token/", views.auth_token, name="api_token_auth"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("best_bank_as.urls")),
]

best_bank_as/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    """Overriding the default user model."""

    groups = models.ManyToManyField(
        "auth.Group",
        verbose_name="groups",
        blank=True,
        help_text="The groups this user belongs to. "
        "A user will get all permissions granted to each of their groups.",
        related_name="custom_user_set",  # Unique related_name
        related_query_name="custom_user",
    )

    user_permissions = models.ManyToManyField(
        "auth.Permission",
        verbose_name="user permissions",
        blank=True,
        help_text="Specific permissions for this user.",
        related_name="custom_user_set",  # Unique related_name
        related_query_name="custom_user",
    )

    @property
    def is_customer(self) -> bool:
        """Check if user is a customer."""
        return hasattr(self, "customer")

    @property
    def is_employee(self) -> bool:
        """Check if the user is an employee or a supervisor."""
        return self.groups.filter(name__in=["employee", "supervisor"]).exists()

best_bank_as/models/account.py
from decimal import Decimal
from typing import TYPE_CHECKING, Any

from django.db import models
from django.db.models import OuterRef, Subquery, Sum

from best_bank_as import enums
from best_bank_as.enums import AccountStatus
from best_bank_as.models.core import base_model
from best_bank_as.models.ledger import Ledger

if TYPE_CHECKING:
    from best_bank_as.models.customer import Customer


class Account(base_model.BaseModel):
    """Model for account."""

    customer = models.ForeignKey(
        "best_bank_as.Customer", on_delete=models.CASCADE, null=True, blank=True
    )  # noqa: E501
    account_type = models.IntegerField(
        choices=enums.AccountType.choices,
        default=enums.AccountType.SAVINGS,
    )
    account_status = models.IntegerField(
        choices=enums.AccountStatus.choices, default=enums.AccountStatus.INACTIVE
    )  # noqa: E501

    @property
    def account_number(self) -> str:
        """Get account number."""
        return self.pk

    def get_balance(self) -> Decimal:
        """
        Retrieve the balance for the account.
        """
        balance = Ledger.objects.filter(account=self).aggregate(Sum("amount"))[
            "amount__sum"
        ]
        return balance or Decimal(0)

    def get_transactions(self) -> list[dict[str, Any]]:
        """
        Retrieve all transactions related to the account.

        Returns:
        List of transactions with:
        - transaction_id: ID of the transaction
        - counterpart_account_number: Account number of the counterpart
        in the transaction # noqa: E501
        - amount: Amount involved in the transaction
        (positive if credit, negative if debit) # noqa: E501
        - date: Transaction date
        """

        counterpart_subquery = (
            Ledger.objects.filter(transaction_id=OuterRef("transaction_id"))
            .exclude(account=self)
            .values("account_id")[:1]
        )

        # Fetch transactions with related counterpart account information
        transactions = (
            Ledger.objects.filter(account=self)
            .annotate(counterpart_account_number=Subquery(counterpart_subquery))
            .values(
                "transaction_id", "amount", "created_at", "counterpart_account_number"
            )
            .order_by("transaction_id")
        )

        return list(transactions)

    @classmethod
    def request_new_account(
        cls, customer: "Customer", status: enums.AccountStatus
    ) -> "Account":
        """Request a new account."""

        if status == AccountStatus.PENDING:
            has_pending_account = cls.objects.filter(
                customer=customer,
                account_status=AccountStatus.PENDING,
            ).exists()

            if has_pending_account:
                error = "You already have a pending account. Please wait for approval."
                raise ValueError(error)

        # Create a new account
        new_account = cls(customer=customer, account_status=status)
        new_account.save()
        return new_account

    def update_account_status(self, status_value: int) -> None:
        self.account_status = status_value
        self.save()

    def __str__(self) -> str:
        return f"Account Number: {self.account_number}, Customer({self.customer})"

best_bank_as/models/bank.py
from django.db import models

from best_bank_as.models.core import base_model


class Bank(base_model.BaseModel):
    """
    Model for banks.
    This will store all banks available for bank to bank transfer.
    """

    reg_number = models.CharField(unique=True, max_length=4)
    bank_name = models.CharField(max_length=255)
    branch_name = models.CharField(max_length=255)
    url = models.CharField(max_length=255)

best_bank_as/models/customer.py
from typing import Any

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q, QuerySet, Sum
from django.db.transaction import atomic

from best_bank_as import enums
from best_bank_as.models.account import Account
from best_bank_as.models.core.base_model import BaseModel
from best_bank_as.models.ledger import Ledger
from best_bank_as.models.loan import Loan
from best_bank_as.models.loan_application import LoanApplication


class Customer(BaseModel):
    """Model for customer."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    rank = models.IntegerField(
        choices=enums.CustomerRank.choices,
        default=2,
        editable=False,
    )
    status = models.IntegerField(
        choices=enums.CustomerStatus.choices,
        default=1,
        editable=True,
    )

    def get_accounts(self) -> QuerySet[Account]:
        """Retrieve all accounts for a give user."""
        accounts = Account.objects.filter(customer_id=self.pk)

        for account in accounts:
            balance = (
                Ledger.objects.filter(account=account).aggregate(Sum("amount"))[
                    "amount__sum"
                ]
                or 0
            )
            account.balance = balance

        return accounts

    def update_status(self, status: enums.CustomerStatus) -> "Customer":
        """Method for updating status on the customer."""
        self.status = status
        self.save()
        return self

    def update_rank(self, rank: int) -> None:
        """Method for updating rank on the customer."""
        self.rank = rank
        self.save()

    def set_customer_active_status(self) -> "Customer":
        """Set customer status.
        This will act as a solft delete.
        """
        self.user.is_active = not self.user.is_active
        self.user.save()
        return self

    def update_customer_fields(self, **kwargs: Any) -> "Customer":
        """Update customer fields."""
        for key, value in kwargs.items():
            if value is not None and value != "":
                if key == "phone_number":
                    setattr(self, key, value)
                else:
                    setattr(self.user, key, value)
        self.user.save()
        self.save()
        return self

    @atomic
    def create_loan(self, loan_application: LoanApplication) -> None:
        """Create a loan for the customer."""
        if not self.can_loan or not loan_application.approved:
            raise ValueError("Customer cannot create this loan.")

        loan_account = Account.objects.create(
            customer=self,
            account_type=enums.AccountType.LOAN,
            account_status=enums.AccountStatus.ACTIVE,
        )
        loan = Loan.objects.create(
            loan_application=loan_application,
            loan_account=loan_account,
        )

        internal_account = Account.objects.get(
            account_type=enums.AccountType.INTERNAL, customer=None
        )

        Ledger.transfer(
            source_account=internal_account,
            destination_account=loan_account,
            amount=loan_application.amount,
        )
        loan.save()

    @property
    def can_loan(self) -> bool:
        """Check if customer can loan."""
        return self.rank >= enums.CustomerRank.BLUE

    @property
    def loan_applications(self) -> list[tuple[LoanApplication, str]]:
        """Get all loan applications for the customer."""
        return LoanApplication.filter_fmt(customer_id=self.pk)

    @classmethod
    def search(cls, query: str) -> QuerySet["Customer"]:
        """Search for customers based on phone number, username, or account number."""
        return (
            cls.objects.filter(
                Q(phone_number__icontains=query) | Q(user__username__icontains=query)
            )
            .distinct()
            .select_related("user")
            # .prefetch_related(Prefetch("account_set"))
        )

    @classmethod
    def get_pending(cls) -> QuerySet["Customer"]:
        """Get all pending customers."""
        return (
            cls.objects.filter(status=enums.CustomerStatus.PENDING).select_related(
                "user"
            )
            # .prefetch_related(Prefetch("account_set"))
        )

    def __str__(self) -> str:
        return f"ID: {self.pk}, Username: {self.user.username}, Rank: {self.rank}"

best_bank_as/models/loan.py
from django.db import models
from django.utils.timezone import now

from best_bank_as import enums
from best_bank_as.models.core import base_model


class Loan(base_model.BaseModel):
    """Model for loan."""

    loan_application = models.OneToOneField(
        "LoanApplication", on_delete=models.CASCADE, null=True, blank=True
    )
    loan_account = models.OneToOneField(
        "Account", on_delete=models.CASCADE, null=True, blank=True
    )
    start_date = models.DateTimeField(default=now)
    status = models.IntegerField(
        choices=enums.LoanStatus.choices,
        default=enums.LoanStatus.IN_PROGRESS,
    )

best_bank_as/models/transaction.py
from best_bank_as.models.core import base_model


class Transaction(base_model.BaseModel):
    """Model for transactions."""

    ...

best_bank_as/forms/TransferForm.py
import os
from typing import Any

from django import forms
from django.contrib.auth.models import User

from best_bank_as.db_models.account import Account
from best_bank_as.enums import AccountStatus


class TransferForm(forms.Form):
    """Form for transferring money."""

    source_account = forms.ModelChoiceField(
        queryset=Account.objects.none(), label="Source Account"
    )

    registration_number = forms.CharField(label="Destination Registration Number")
    destination_account = forms.IntegerField(label="Destination Account Number")
    amount = forms.DecimalField(decimal_places=2, label="Amount to Transfer")

    def __init__(self, user: User, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["source_account"].queryset = Account.objects.filter(
            customer=user.customer, account_status=AccountStatus.ACTIVE
        )
        self.fields["registration_number"].widget.attrs["placeholder"] = os.environ[
            "BANK_REGISTRATION_NUMBER"
        ]

best_bank_as/forms/customer_form.py
from typing import Any

from django import forms
from django.contrib.auth import get_user_model

from best_bank_as.db_models.customer import Customer

User = get_user_model()


class UserCreationForm(forms.ModelForm):
    """User form."""

    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password"]

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["placeholder"] = "BestCustomer34"
        self.fields["first_name"].widget.attrs["placeholder"] = "First Name"
        self.fields["last_name"].widget.attrs["placeholder"] = "Last Name"
        self.fields["email"].widget.attrs["placeholder"] = "customer@best_bank_as.com"
        self.fields["password"].widget.attrs["placeholder"] = "******"


class CustomerCreationForm(forms.ModelForm):
    """Customer form."""

    phone_number = forms.CharField(widget=forms.NumberInput())

    class Meta:
        model = Customer
        fields = ["phone_number"]

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["phone_number"].widget.attrs["placeholder"] = "11223344"


class CustomerApproveForm(forms.ModelForm):
    """Customer form."""

    class Meta:
        model = Customer
        fields = ["status"]


class UserCreationByEmployeeForm(UserCreationForm):
    """User form when employee creates a user."""

    class Meta(UserCreationForm.Meta):
        exclude = ("password",)

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Init method."""
        super().__init__(*args, **kwargs)
        # Since 'password' field is excluded, we remove it from the fields
        if "password" in self.fields:
            self.fields.pop("password")


class UserUpdateForm(UserCreationForm):
    """Form for updating a user instance."""

    class Meta(UserCreationForm.Meta):
        exclude = ("password",)

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = False

        if "password" in self.fields:
            self.fields.pop("password")


class CustomerUpdateForm(CustomerCreationForm):
    """Form for updating a customer instance."""

    class Meta(CustomerCreationForm.Meta):
        pass

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["phone_number"].required = False

best_bank_as/forms/external_transfer_form.py
from django import forms


class ExternalTransferForm(forms.Form):
    """Form for external transfer."""

    destination_account = forms.IntegerField()
    amount = forms.DecimalField(decimal_places=2)
    registration_number = forms.CharField()

best_bank_as/forms/loan_application_form.py
from typing import Any

from django import forms


class LoanApplicationForm(forms.Form):
    """Form for loan application."""

    def __init__(self, *args: Any, **kwargs: Any):
        """Override init to pass in customer."""
        self.customer = kwargs.pop("customer")
        super().__init__(*args, **kwargs)

    reason = forms.CharField(label="Reason", max_length=255)
    amount = forms.DecimalField(label="Amount", max_digits=10, decimal_places=2)

best_bank_as/forms/request_new_account_form.py
from django import forms


class NewAccountRequestForm(forms.Form):
    """Form to request a new account.
    No fields needed since we're only signaling an intent."""

    pass

best_bank_as/templates/best_bank_as/customers/customer_active_status.html
{% if customer.user.is_active %}
    <button
            hx-delete="{% url 'best_bank_as:customer' customer.pk %}"
            hx-headers='{"X-CSRFToken":"{{ csrf_token }}", "Content-Type": "application/json"}'
            hx-swap="outerHTML"
            type="submit">Set inactive
    </button>
{% else %}
    <button
            hx-delete="{% url 'best_bank_as:customer' customer.pk %}"
            hx-headers='{"X-CSRFToken":"{{ csrf_token }}", "Content-Type": "application/json"}'
            hx-swap="outerHTML"
            type="submit">Set active
    </button>
{% endif %}

best_bank_as/templates/best_bank_as/customers/customer_rank_partial.html
<select name="customer_rank" id="customer_rank"
        hx-put="{% url 'best_bank_as:customer' customer.pk %}"
        hx-headers='{"X-CSRFToken":"{{ csrf_token }}", "Content-Type": "application/json"}'
        hx-trigger="change delay:1500ms"
        hx-swap="outerHTML"
        style="text-transform: capitalize"
>
    <option hidden> {{ customer.get_rank_display }}</option>

    {% for rank_name, rank_value in rank_list %}
        <option value="{{ rank_value }}">{{ rank_name.lower }}</option>
    {% endfor %}
</select>

{% include "best_bank_as/messages/messages.html" %}

best_bank_as/templates/best_bank_as/customers/customer_update.html
<article>
    <form
            hx-put="{% url "best_bank_as:customer" customer.pk %}"
            hx-headers='{"X-CSRFToken":"{{ csrf_token }}", "Content-Type": "application/json"}'
            hx-swap="outerHTML"
    >

        <input hidden name="customer_update" value="customer_update" type="text">
        <input hidden name="customer_pk" value="{{ customer.pk }}" type="text">
        {% csrf_token %}
        {{ updateForm }}
        {{ updateCustomerForm }}

        <button type="submit">Update</button>
    </form>
</article>

{% include "best_bank_as/messages/messages.html" %}

best_bank_as/templates/best_bank_as/customers/customers_approve_list.html
<thead>
    <tr>
        <th>User name</th>
        <th>Phone</th>
        <th>Actions</th>
    </tr>
</thead>
<tbody>
{% for customer in customers %}
    <tr>
        <td>{{ customer.user.username }}</td>
        <td>{{ customer.phone_number }}</td>
        <td>
            <button hx-put="{% url 'best_bank_as:customers_approve_details' customer.pk %}"
                    hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'>
                Approve
            </button>
            <button hx-delete="{% url 'best_bank_as:customers_approve_details' customer.pk %}"
                    hx-confirm="Are you sure you want to reject the customer?"
                    hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'>
                Reject
            </button>
        </td>
    </tr>
{% endfor %}
</tbody>

best_bank_as/templates/best_bank_as/customers/customers_detail.html
{% extends "best_bank_as/base.html" %}

{% block content %}
    <h1>Search Results for "{{ query }}"</h1>

    {% if customers %}
        {% for customer in customers %}
            <h2>Customer details</h2>
            <table border="1">
                <thead>
                <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Customer Level</th>
                    <th>Customer Status</th>
                </tr>
                </thead>
                <tbody>
                <tr>

                    <td>
                        <a href="{% url 'best_bank_as:staff_account_list' customer.user.pk %}">{{ customer.user.username }}</a>
                    </td>
                    <td>{{ customer.user.first_name }}</td>
                    <td>{{ customer.user.last_name }}</td>
                    <td>{{ customer.user.email }}</td>
                    <td>{{ customer.phone_number }}</td>
                    <td>{% include "best_bank_as/customers/customer_rank_partial.html" %}</td>
                    <td>
                        {% include "best_bank_as/customers/customer_active_status.html" %}
                    </td>

                </tr>
                </tbody>
            </table>
            <h2>Customer accounts</h2>
            <table border="1">
                <thead>
                <tr>
                    <th>Account Number</th>
                    <th>Account Type</th>
                    <th>Account Status</th>
                </tr>
                </thead>
                <tbody>
                {% for account in customer.account_set.all %}
                    <tr>
                        <td>
                            <a href="{% url 'best_bank_as:account_details' account.pk %}">{{ account.account_number }}</a>
                        </td>
                        <td>{{ account.get_account_type_display }}</td>
                        <td>
                            {% include "best_bank_as/accounts/account_status_partial.html" %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <form action="{% url 'best_bank_as:account_list' %}" method="post">
                <input hidden name="account_status" value="ACTIVE" type="text">
                <input hidden name="customer_pk" value="{{ customer.pk }}" type="text">
                {% csrf_token %}
                <button>Create account</button>
            </form>

            <div>
                <h2>Update user</h2>
                {% include "best_bank_as/customers/customer_update.html" %}
            </div>
        {% endfor %}
    {% else %}
        <p>No customers found.</p>
    {% endif %}
{% endblock %}

best_bank_as/templates/best_bank_as/customers/customers_pending.html
{% extends "best_bank_as/base.html" %}

{% block content %}
<div class="container">
    <h2>Pending Customers</h2>


    <table class="table" hx-target="this" hx-swap="outerHTML">
        {% include "best_bank_as/customers/customers_approve_list.html" %}
    </table>
    
</div>
{% endblock %}

best_bank_as/templates/best_bank_as/customers/customers_search.html
{% extends "best_bank_as/base.html" %}

{% block content %}
    <h1>Search Results for "{{ query }}"</h1>

    {% if customers %}
        {% for customer in customers %}
            <h2>Customer details</h2>
            <table border="1">
                <thead>
                <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Customer Level</th>
                    <th>Customer Status</th>
                </tr>
                </thead>
                <tbody>
                <tr>

                    <td>
                        <a href="{% url 'best_bank_as:get_accounts_for_user' customer.user.pk %}">{{ customer.user.username }}</a>
                    </td>
                    <td>{{ customer.user.first_name }}</td>
                    <td>{{ customer.user.last_name }}</td>
                    <td>{{ customer.user.email }}</td>
                    <td>{{ customer.phone_number }}</td>
                    <td>{% include "best_bank_as/customers/customer_rank_partial.html" %}</td>
                    <td>
                        {% include "best_bank_as/customers/customer_active_status.html" %}
                    </td>

                </tr>
                </tbody>
            </table>
            <h2>Customer accounts</h2>
            <table border="1">
                <thead>
                <tr>
                    <th>Account Number</th>
                    <th>Account Type</th>
                    <th>Account Status</th>
                </tr>
                </thead>
                <tbody>
                {% for account in customer.account_set.all %}
                    <tr>
                        <td>
                            <a href="{% url 'best_bank_as:get_details' account.pk %}">{{ account.account_number }}</a>
                        </td>
                        <td>{{ account.get_type_display }}</td>
                        <td>
                            {% include "best_bank_as/accounts/account_status_partial.html" %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <form action="{% url 'best_bank_as:get_accounts_list' %}" method="post">
                <input hidden name="account_status" value="ACTIVE" type="text">
                <input hidden name="customer_pk" value="{{ customer.pk }}" type="text">
                {% csrf_token %}
                <button>Create account</button>
            </form>

            <div>
                <h2>Update user</h2>
                {% include "best_bank_as/customers/customer_update.html" %}
            </div>
        {% endfor %}
    {% else %}
        <p>No customers found.</p>
    {% endif %}
{% endblock %}

best_bank_as/templates/best_bank_as/customers/customers_table.html
<thead>
    <tr>
        <th>User name</th>
        <th>Phone</th>
        <th>Actions</th>
    </tr>
</thead>
<tbody>
{% for customer in customers %}
    <tr>
        <td>{{ customer.user.username }}</td>
        <td>{{ customer.phone_number }}</td>
        <td>
            <button hx-put="{% url 'best_bank_as:approve_customers_details' customer.pk %}"
                    hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'>
                Approve
            </button>
            <button hx-delete="{% url 'best_bank_as:approve_customers_details' customer.pk %}"
                    hx-confirm="Are you sure you want to reject the customer?"
                    hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'>
                Reject
            </button>
        </td>
    </tr>
{% endfor %}
</tbody>